home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

strata/urls.py
from django.conf.urls import url
from django.shortcuts import redirect

from . import views

app_name = 'strata'
urlpatterns = [
    url(r'^$', lambda _: redirect('home:index'), name='index'),
    url(r'^servers/app/$', views.StrataAppServersView.as_view(), name='app_servers' ),
    url(r'^servers/assentis/$', views.StrataAssentisServersView.as_view(), name='assentis_servers' ),
    url(r'^servers/orb/$', views.StrataORBServersView.as_view(), name='orb_servers' ),
]

stratahq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth import views as auth_views

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},  name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    # Admin site
    url(r'^admin/', admin.site.urls),
    # Redirect root to /admin
    url(r'^$', lambda _: redirect('home:index'), name='index'),
    # The home app
    url(r'^home/', include('home.urls')),
    # The assets app
    url(r'^assets/', include('assets.urls')),
    # The Strata app
    url(r'^strata/', include('strata.urls')),
]

assets/models.py
from django.db import models
from management.models import Environment, _TEAMS
from .validators import is_valid_hostname, is_unprivileged_port
from .utils import timedgethostbyname
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.core.cache import cache
from .services import all_jobs

_SERVERROLES = (
    ('app', 'Strata App Server'),
    ('ass', 'Assentis Server'),
    ('orb', 'ORBS Server'),
    ('lb', 'HAProxy Load Balancer'),
    ('ovm', 'OVM Host'),
    ('vm', 'VMWare Host'),
)

_OS = (
    ('el6', 'CentOS 6'),
    ('el7', 'CentOS 7'),
    ('win2k8', 'Windows Server 2008'),
    ('win2k12', 'Windows Server 2012'),
    ('vmware', 'VMWare ESXi'),
    ('ovm', 'Oracle Virtual Machine'),
)

_WEBLOGIC_EDITIONS = (
    ('developer', 'Developer Edition'),
    ('standard', 'Standard Edition'),
    ('enterprise', 'Enterprise Edition'),
)

_TOMCAT_VERSIONS = (
    ('7', 'Tomcat 7'),
    ('8', 'Tomcat 8'),
)

_SERVER_STATUSES = (
    ('blank', 'Needs Provisioning'),
    ('installed', 'OS Installed'),
    ('unassigned', 'Unassigned'),
    ('live', 'Live System'),
    ('maintenance', 'Out for Maintenance'),
    ('broken', 'Needs Fixing'),
    ('burn', 'Can be Humanely Destroyed'),
    ('decom', 'Decommisioned'),
)

_APPLICATION_STATUSES = (
    ('develop', 'Under Development'),
    ('production', 'In Production'),
    ('retired', 'Retired'),
)

_TASK_STATUSES = (
    ('success', 'SUCCESS'),
    ('running', 'IN PROGRESS'),
    ('failed', 'FAILED'),
    ('rollback', 'ROLLBACK'),
)

class Server(models.Model):
    """
    A server, this is used as a class to extend application specific servers from such as a WebLogic server.
    """
    name = models.CharField(max_length=255, db_index=True, unique=True, validators=[is_valid_hostname],
                            help_text='The FQDN of the server.')
    role = models.CharField(max_length=8, choices=_SERVERROLES)
    owner = models.CharField(max_length=8, choices=_TEAMS, default='server')
    primary_ip = models.GenericIPAddressField(verbose_name='Primary IP', blank=True, null=True, unique=True,
                                              help_text='Usually assigned to eth0 or ens160. Leave blank to try and resolve.')
    environment = models.ForeignKey(Environment)
    status = models.CharField(max_length=32, choices=_SERVER_STATUSES, default='live')
    override_puppet_role = models.CharField(max_length=64, blank=True, null=True)
    override_puppet_environment = models.CharField(max_length=64, blank=True, null=True)
    is_virtual = models.BooleanField(default=False)
    virtual_host = models.ForeignKey('HypervisorHost', null=True, blank=True)
    os = models.CharField(verbose_name='OS', max_length=8, choices=_OS, null=True, blank=True)
    cpus = models.PositiveSmallIntegerField(default=1)
    cores = models.PositiveSmallIntegerField(default=0)
    ram = models.PositiveSmallIntegerField(default=0)

    class Meta(object):
        ordering = ('name',)

    def clean(self, *args, **kwargs):
        try:
            if self.stratacustomerstack_set.get()[0].environment is not self.environment:
                raise ValidationError(
                    _('Server is in use by: %(customer_stack)s. Cannot move environment.'),
                    params={'customer_stack': self.stratacustomerstack_set.get()},
                )
        except:
            pass

        try:
            if self.stratacustomerstack_set.get()[0].stack.valid_target is not self.role:
                raise ValidationError(
                    _('Server is in use by: %(customer_stack)s. Cannot move environment.'),
                    params={'customer_stack': self.stratacustomerstack_set.get()},
                )
        except:
            pass

        super(Server, self).clean(*args, **kwargs)


    def save(self, *args, **kwargs):
        """If the primary ip address wasn't known, we try to resolve it on save"""
        if self.primary_ip is '':
            self.primary_ip = timedgethostbyname(self.name)

        super(Server, self).save(*args, **kwargs)

    def puppet_role(self):
        """
        Return the Puppet role assigned to this server
        """
        try:
            if self.override_puppet_role is not None:
                return self.override_puppet_role
            else:
                return PuppetRole.objects.all().filter(role=self.role)[0].puppet_role
        except:
            return None

    def puppet_environment(self):
        """
        Return the Puppet environment assigned to this server
        """
        try:
            if self.override_puppet_environment is not None:
                return self.override_puppet_environment
            else:
                return self.environment.short_name
        except:
            return None

    def connect_to(self):
        """
        Returns the primary ip address or the hostname to connect to
        """
        if self.primary_ip is not None:
            return self.name
        else:
            return self.name


    def total_cores(self):
        """
        Total number of cores on this server
        """
        try:
            return self.cpus * self.cores
        except:
            return None

    def __str__(self):
        return self.name


class HypervisorHost(Server):
    """
    A hypervisor host is used for the relationship between host / vm
    and reporting things like WebLogic licences etc... 
    """
    def guest_servers(self):
        return self.server_set.all()

    def __str__(self):
        return self.name


class WeblogicServer(Server):
    """
    Weblogic servers have added WebLogic stuff
    """
    edition = models.CharField(max_length=16, choices=_WEBLOGIC_EDITIONS, default='standard')
    nodemanager_port = models.PositiveSmallIntegerField(validators=[is_unprivileged_port], default=5666)
    nodemanager_ssl = models.BooleanField(default=False)
    adminserver_port = models.PositiveSmallIntegerField(validators=[is_unprivileged_port], default=7001)
    adminserver_ssl = models.BooleanField(default=False)
    adminserver_user = models.CharField(max_length=256, default='weblogic')
    adminserver_pass = models.CharField(max_length=256, default='letmein1')

    def __str__(self):
        return self.name

class WindowsServer(Server):
    """
    Windows servers have Windows stuff
    """

    def __str__(self):
        return self.name


class TomcatServer(Server):
    """
    Tomcat servers have added Tomcat stuff
    """
    version = models.CharField(max_length=8, choices=_TOMCAT_VERSIONS, default='8')

    def __str__(self):
        return self.name


class PuppetRole(models.Model):
    """
    A server's role can be linked to a Puppet role.
    """
    role = models.CharField(max_length=8, choices=_SERVERROLES, unique=True)
    description = models.TextField(max_length=512)
    # Auto-generated on save
    puppet_role = models.CharField(max_length=32, help_text='Autogenerated Puppet role applied to this server')

    def save(self, *args, **kwargs):
        self.puppet_role = '::role::%s' % self.role
        super(PuppetRole, self).save(*args, **kwargs)

    class Meta(object):
        ordering = ('role',)

    def __str__(self):
        return self.get_role_display()


class Application(models.Model):
    """
    An application is an asset too. This base class is used to extend upon
    in team specific classes.
    """
    name = models.CharField(max_length=32, unique=True)
    short_name =  models.CharField(max_length=16, unique=True)
    description = models.TextField(max_length=512)
    status = models.CharField(max_length=32, choices=_APPLICATION_STATUSES, default='production')
    # This should be set in team specific Save method
    owner = models.CharField(max_length=8, choices=_TEAMS)

    default_port = models.PositiveSmallIntegerField(validators=[is_unprivileged_port], null=True, blank=True)
    default_ssl_port = models.PositiveSmallIntegerField(validators=[is_unprivileged_port], null=True, blank=True)
    default_jmx_port = models.PositiveSmallIntegerField(validators=[is_unprivileged_port], null=True, blank=True)
    healthcheck_url = models.CharField(max_length=64, default='/healthcheck')
    has_healthcheck = models.BooleanField(default=False)

    nexus_url = models.URLField(null=True, blank=True,
                                help_text='URL to Nexus assets')
    pre_deploy_job = models.CharField(max_length=32, null=True, blank=True, choices=all_jobs(),
                                  help_text='The name of the Jenkins job to run before deploying this application')
    deploy_job = models.CharField(max_length=32, null=True, blank=True, choices=all_jobs(),
                                      help_text='The name of the Jenkins job to deploy this application')
    post_deploy_job = models.CharField(max_length=32, null=True, blank=True, choices=all_jobs(),
                                      help_text='The name of the Jenkins job to run after deploying this application')

    class Meta(object):
        ordering = ('name',)

    def __str__(self):
        return self.name


class ApplicationStack(models.Model):
    """
    An application stack is a collection (or 1) of applications that are deloyed together for something to run.
    """
    name = models.CharField(max_length=32)
    short_name =  models.CharField(max_length=16, unique=True)
    # This should be set in team specific Save method
    owner = models.CharField(max_length=8, choices=_TEAMS)
    description = models.TextField(max_length=512)
    valid_target = models.CharField(max_length=32, choices=_SERVERROLES, null=True, blank=True,
                                    help_text='What server role can this stack be deployed onto?')
    pre_deploy_job = models.CharField(max_length=32, null=True, blank=True, choices=all_jobs(),

strata/forms.py
from django import forms
from .models import StrataServer

class ServerForm(forms.ModelForm):
    class Meta:
        model = StrataServer
        fields = ['override_puppet_role', 'override_puppet_environment', 'status']

strata/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from assets.models import _SERVER_STATUSES, ServerRoleTask
from assets.tasks import run_jenkins_job
from .models import StrataServer
from .forms import ServerForm
from stratahq.settings import JENKINS

import json

class StrataServerView(LoginRequiredMixin, generic.ListView):
    """
    Base Server view as many of our views / forms are the same with minor changes
    """
    login_url = '/login'
    redirect_field_name = 'next'
    template_name = 'strata/servers.html'
    model = StrataServer
    server_form = ServerForm()

class StrataAppServersView(StrataServerView):
    """
    Strata App Server view
    """
    queryset = StrataServer.objects.filter(role='app').order_by('name')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(StrataAppServersView, self).get_context_data(**kwargs)
        context['server_role'] = 'app'
        context['server_form'] = self.server_form
        context['server_statuses'] = _SERVER_STATUSES
        context['server_tasks'] = ServerRoleTask.objects.get(role='app').tasks.all()
        context['jenkins_server'] = JENKINS['SERVER']
        return context

    def post(self, request, *args, **kwargs):
        server = StrataServer.objects.get(pk=request.POST.get('pk'))
        form = ServerForm(request.POST, instance=server)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect('/strata/servers/app/#%s' % server.name)

    def get(self, request, *args, **kwargs):
        try:
            if request.GET['action']:
                run_jenkins_job(request.GET['action'], { "server": request.GET['server']})
        except:
            pass

        return super(StrataAppServersView, self).get(request, *args, **kwargs)

class StrataAssentisServersView(StrataServerView):
    """
    Assentis Server view
    """
    queryset = StrataServer.objects.filter(role='ass').order_by('name')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(StrataAssentisServersView, self).get_context_data(**kwargs)
        # Add in a QuerySet of last 20 tasks
        context['server_role'] = 'Assentis'
        return context


class StrataORBServersView(StrataServerView):
    """
    ORB Server view
    """
    queryset = StrataServer.objects.filter(role='orb').order_by('name')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(StrataORBServersView, self).get_context_data(**kwargs)
        # Add in a QuerySet of last 20 tasks
        context['server_role'] = 'ORB'
        return context

strata/templates/strata/nav.html
<li class="{% if "/strata/" in request.get_full_path %}active{% endif %}">
    <a href="/strata/"><i class="fa fa-desktop"></i> <span class="nav-label">Strata</span><span class="fa arrow"></span></a>
    <ul class="nav nav-second-level{% if "/strata/" not in request.get_full_path %} collapse{% endif %}">
        <li class="{% if "/strata/servers/" in request.get_full_path %}active{% endif %}">
            <a href="#">
                <i class="fa fa-server" aria-hidden="true"></i> <span class="nav-label">Servers</span>
                <span class="fa arrow"></span>
            </a>
            <ul class="nav nav-third-level">
                <li class="{% if "/strata/servers/app/" in request.get_full_path %}active{% endif %}">
                    <a href="/strata/servers/app/">Strata App Servers</a>
                </li>
                <li class="{% if "/strata/servers/assentis/" in request.get_full_path %}active{% endif %}">
                    <a href="/strata/servers/assentis/">Assentis Servers</a>
                </li>
                <li class="{% if "/strata/servers/orb/" in request.get_full_path %}active{% endif %}">
                    <a href="/strata/servers/orb/">ORB Servers</a>
                </li>
            </ul>
        </li>
        <li class="{% if request.get_full_path == "/strata/environments/" %}active{% endif %}">
            <a href="/strata/environments/"><i class="fa fa-cloud" aria-hidden="true"></i> Environments</a>
        </li>
        <li class="{% if request.get_full_path == "/strata/deployments/" %}active{% endif %}">
            <a href="/strata/deployments/"><i class="fa fa-cloud-upload" aria-hidden="true"></i> Deployments</a>
        </li>
    </ul>
</li>

strata/templates/strata/server_form.html
<div class="ibox-content">
    <form method="post" action="#{{ server.name }}">
        {% csrf_token %}
        <input type="hidden" name="pk" value="{{ server.pk }}">
        <h3>Puppet Override</h3>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_override_puppet_role">Role:</label>
            <div class="col-sm-10"><input type="text" class="form-control" name="override_puppet_role" id="id_override_puppet_role"{% if server.override_puppet_role != None %} value="{{ server.override_puppet_role }}"{% endif %}/></div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_override_puppet_environment">Environment:</label>
            <div class="col-sm-10"><input type="text" class="form-control" name="override_puppet_environment" id="id_override_puppet_environment"{% if server.override_puppet_environment != None %} value="{{ server.override_puppet_environment }}"{% endif %}/></div>
        </div>
        <h3>Server Status</h3>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="id_status">Status:</label>
            <div class="col-sm-10">
                <select class="form-control m-b" id="id_status" name="status">
                    {% for state in server_statuses %}
                        <option value="{{ state.0 }}"{% if server.status == state.0 %} selected{% endif %}>{{ state.1 }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <button class="btn btn-primary" value="server_form" type="submit">Save changes</button>
    </form>
</div>

strata/templates/strata/server_tasks.html
<div class="ibox-content">
    <h3>Server Tasks</h3>
    {% for task in server_tasks %}
        <a href="?action={{ task }}&server={{ server.name }}#{{ server.name }}"
           class="btn btn-primary btn-md">{{ task }}</a>
    {% endfor %}
</div>
{% if request.GET.action %}
    <div class="ibox-content">
        <pre><div id="actionlog"></div></pre>

        <script type="text/javascript">

            function getLatestBuildNumber(callback) {
                var serverBuildNumbers = [];
                $.getJSON("{{ jenkins_server }}/job/{{ request.GET.action }}/api/json?tree=builds[url]", function (data) {
                    var buildUrls = [];
                    $.each(data.builds, function (i, val) {
                        buildUrls.push(val.url);
                    });
                    $.each(buildUrls, function (i, buildUrl) {
                        $.getJSON(buildUrl + "/api/json", function (buildInfo) {
                            $.each(buildInfo.actions, function (i, action) {
                                if (action.parameters) {
                                    $.each(action.parameters, function (i, parameter) {
                                        if (parameter.name == "server" && parameter.value == "{{ server.name }}") {
                                            serverBuildNumbers[buildInfo.number] = buildInfo.number;
                                        }
                                    });
                                }
                            });
                        });
                    });
                });
                setTimeout(function () {
                    bnums = serverBuildNumbers.filter(Number);
                    callback(bnums[bnums.length - 1]);
                }, 1000);
            }

            function tailLog(lastBuildNumber, currentBuildNumber) {
                if (lastBuildNumber !== currentBuildNumber) {
                    setInterval(function () {
                        $("#actionlog").load("{{ jenkins_server }}/job/{{ request.GET.action }}/" + currentBuildNumber + "/consoleText", function (response) {
                            $("#actionlog").html(response.split("\n").slice(-18).join("\n"));
                        });
                    }, 1000);
                } else {
                    $("#actionlog").text("Loading log...");
                }
            }

            function getCurrentBuildNumber(callback) {
                getLatestBuildNumber(function (currentBuildNumber) {
                    callback(currentBuildNumber)
                });
            }

            $(document).ready(function () {
                // Trick the "Loading log..." message into been displayed
                tailLog(0, 0);
                var lastBuildNumber = 0;
                var currentBuildNumber = 0;
                var buildTestTimer = setInterval(function () {
                    getCurrentBuildNumber(function (buildNumber) {
                        if (!(lastBuildNumber > 0 && lastBuildNumber !== buildNumber)) {
                            lastBuildNumber = buildNumber;
                        } else {
                            clearInterval(buildTestTimer);
                            currentBuildNumber = buildNumber;
                            tailLog(lastBuildNumber, currentBuildNumber);
                        }
                    });
                }, 1000);
            });
        </script>
    </div>
{% endif %}

strata/templates/strata/servers.html
{% extends 'base.html' %}

{% block title %}Strata Servers{% endblock %}
{% block pageclass %}gray-bg{% endblock %}

{% load weblogic_tags %}
{% load badge_tags %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>{{ server_role|title }} Servers</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/home/">Home</a>
                </li>
                <li>
                    Strata
                </li>
                <li>
                    Servers
                </li>
                <li class="active">
                    <strong>{{ server_role|title }} Servers</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="ibox-content">
        {% if strataserver_list %}
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Hostname</th>
                    <th>Puppet Role</th>
                    <th>Environment</th>
                    {% comment %}
                    There's certain things we only want to show for specific server types.
                    Rather than separate templates or funky includes I'm doing it inline for the sake of
                    visibility.
                    {% endcomment %}
                    {% if server_role == 'app' %}
                        <th>Nodemanager</th>
                        <th>AdminServer</th>
                        <th>Managed Servers</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for server in strataserver_list %}
                    <tr class="modal-row" data-toggle="modal" data-target="#{{ server.name }}">
                        <td>{{ server.name }}</td>
                        <td>{{ server.puppet_role }}</td>
                        <td>{{ server.environment }}</td>
                        {% if server_role == 'app' %}
                            <td>{{ server.connect_to | tcp_health:server.nodemanager_port }}</td>
                            <td>{{ server.connect_to | tcp_health:server.adminserver_port }}</td>
                            <td>{{ server.connect_to | get_managed_servers }}</td>
                        {%  endif %}
                        {% comment %}
                        Each row will show a modal dialog box for interaction with a server.
                        We'll render in each row avoiding the need to loop through each server
                        object again further down the page. It also means that the modal is
                        all ready to go on click and we don't have to wait for an ajax call / extra
                        http requests.
                        {% endcomment %}
                        <div class="modal inmodal" id="{{ server.name }}" tabindex="-1" role="dialog"  aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                        <h4 class="modal-title">Server: {{ server.name }}</h4>
                                        <small class="font-bold">
                                            {{ server | puppet_role_badge }}
                                            {{ server | puppet_env_badge }}
                                            {{ server | status_badge }}
                                        </small>
                                    </div>
                                    <div class="modal-body">
                                        {% include 'strata/server_form.html' %}
                                        {% include 'strata/server_tasks.html' %}
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                                    </div>
                                    <script type = "text/javascript">
                                        $('#{{ server.name }}').on('hidden.bs.modal', function () {
                                           window.location.href =  window.location.href.split("?")[0]
                                        })
                                    </script>
                                </div>
                            </div>
                        </div>
                    </tr>
                {% endfor %}
                </tbody>
              </table>
        {% else %}
            <p>No servers yet.</p>
        {% endif %}
    </div>
{% endblock content %}