home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

stratahq/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth import views as auth_views

admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},  name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
    # Admin site
    url(r'^admin/', admin.site.urls),
    # Redirect root to /admin
    url(r'^$', lambda _: redirect('home:index'), name='index'),
    # The home app
    url(r'^home/', include('home.urls')),
    # The assets app
    url(r'^assets/', include('assets.urls')),
    # The Strata app
    url(r'^strata/', include('strata.urls')),
]

management/models.py
from django.db import models
from django.contrib.auth.models import User, Group

_TEAMS = (
    ('strata', 'Strata Admin'),
    ('dev', 'Developer'),
    ('webs', 'Web Services'),
    ('server', 'Server Team'),
)

class Customer(models.Model):
    """A customer. A dev squad is also considered a customer."""
    name = models.CharField(max_length=128, unique=True)
    short_name = models.CharField(max_length=16, unique=True)
    environments = models.ManyToManyField('Environment', through='CustomerEnvironment')

    def __str__(self):
        return self.name

# Environment - dev, uat, prd
class Environment(models.Model):
    """An environment such as dev, uat or live."""
    name = models.CharField(max_length=128, unique=True)
    short_name = models.CharField(max_length=8, unique=True)
    agent_tag = models.CharField(max_length=64, default='none')
    api_proxy = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

class CustomerEnvironment(models.Model):
    """A customer can have many environments. This model allows us to extend that relationship and add extra data"""
    customer = models.ForeignKey('Customer', to_field='short_name')
    environment = models.ForeignKey('Environment', to_field='short_name')
    # Auto-generated on save
    name = models.CharField(max_length=64, blank=True, unique=True)

    class Meta:
        ordering = ['customer', 'environment']

    def __str__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        self.name = '%s_%s' % (self.customer.short_name, self.environment.short_name)
        super(CustomerEnvironment, self).save(*args, **kwargs)


class Team(models.Model):
    """This model holds the users / groups assigned to teams"""
    team = models.CharField(unique=True, max_length=32, choices=_TEAMS)
    users = models.ManyToManyField(User, blank=True)
    groups = models.ManyToManyField(Group, blank=True)

    def __str__(self):
        return '%s' % self.get_team_display()

templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
    <title>StrataHQ | {% block title %}{% endblock %}</title>
    {% block style %}{% include 'style.html' %}{% endblock %}
    {% block extrahead %}{% endblock %}
    <script src="{% block js-jquery %}{% static "js/jquery-2.1.1.js" %}{% endblock %}"></script>
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
      data-admin-utc-offset="{% now "Z" %}">

<!-- Wrapper -->
<div id="wrapper">
    {% block sidebar %}{% include 'nav.html' %}{% endblock %}

    <!-- Page Wrapper -->
    <div id="{% block pagewrapperid %}page-wrapper{% endblock %}" class="gray-bg {% block pageclass %}{% endblock %}">
        {% block header %}{% include 'header.html' %}{% endblock %}

        <!-- Content -->
        <div id="content" class="{% block coltype %}colM{% endblock %}">
            {% block messages %}
                {% if messages %}
                    <ul class="messagelist">{% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
                    {% endfor %}</ul>
                {% endif %}
            {% endblock messages %}
            {% block pretitle %}{% endblock %}
            {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
            {% block content %}
                {% block object-tools %}{% endblock %}
                {{ content }}
            {% endblock %}
            <br class="clear" />
        </div><!-- END Content -->

    </div><!-- END Page Wrapper -->

    {% block footer %}<div id="footer"></div>{% endblock %}

</div><!-- END Wrapper -->

{% block scripts %}{% include 'js.html' %}{% endblock %}
</body>
</html>

templates/header.html
<div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="/logout">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>

templates/js.html
{% load static %}
<!-- Mainly scripts -->
<script src="{% block js-bootstrap %}{% static "js/bootstrap.min.js" %}{% endblock %}"></script>
<script src="{% block js-metisMenu %}{% static "js/plugins/metisMenu/jquery.metisMenu.js" %}{% endblock %}"></script>
<script src="{% block js-slimscroll %}{% static "js/plugins/slimscroll/jquery.slimscroll.min.js" %}{% endblock %}"></script>

<!-- Flot -->
<script src="{% block js-flot %}{% static "js/plugins/flot/jquery.flot.js" %}{% endblock %}"></script>
<script src="{% block js-flot-tip %}{% static "js/plugins/flot/jquery.flot.tooltip.min.js" %}{% endblock %}"></script>
<script src="{% block js-flot-spline %}{% static "js/plugins/flot/jquery.flot.spline.js" %}{% endblock %}"></script>
<script src="{% block js-flot-size %}{% static "js/plugins/flot/jquery.flot.resize.js" %}{% endblock %}"></script>
<script src="{% block js-flot-pie %}{% static "js/plugins/flot/jquery.flot.pie.js" %}{% endblock %}"></script>

<!-- Peity -->
<script src="{% block js-peity %}{% static "js/plugins/peity/jquery.peity.min.js" %}{% endblock %}"></script>

<!-- Custom and plugin javascript -->
<script src="{% block js-inspinia %}{% static "js/inspinia.js" %}{% endblock %}"></script>
<script src="{% block js-pace %}{% static "js/plugins/pace/pace.min.js" %}{% endblock %}"></script>

<!-- jQuery UI -->
<script src="{% block js-jquery-ui %}{% static "js/plugins/jquery-ui/jquery-ui.min.js" %}{% endblock %}"></script>

<!-- GRITTER -->
<script src="{% block js-gritter %}{% static "js/plugins/gritter/jquery.gritter.min.js" %}{% endblock %}"></script>

<!-- Sparkline -->
<script src="{% block js-sparkline %}{% static "js/plugins/sparkline/jquery.sparkline.min.js" %}{% endblock %}"></script>

<!-- Sparkline demo data  -->
<script src="{% block js-sparkline-demo %}{% static "js/demo/sparkline-demo.js" %}{% endblock %}"></script>

<!-- ChartJS-->
<script src="{% block js-chartjs %}{% static "js/plugins/chartJs/Chart.min.js" %}{% endblock %}"></script>

<!-- Toastr -->
<script src="{% block js-toastr %}{% static "js/plugins/toastr/toastr.min.js" %}{% endblock %}"></script>

<!-- Enable us to AJAX submit forms (used on modal forms) -->
<script src="{% block js-jquery-form %}{% static "js/jquery.form.js" %}{% endblock %}"></script>

<!-- Allows us to load a modal on request to /url/#modalname -->
<script>
  //shortcut for $(document).ready
  $(function(){
      if(window.location.hash) {
          var modal = window.location.hash;
          $(modal).modal('toggle');
      }
  });
</script>

templates/login.html
{% extends 'base.html' %}
{% block header %}{% endblock %}
{% block sidebar %}{% endblock %}

{% block bodyclass %}gray-bg{% endblock %}
{% block pagewrapperid %}login{% endblock %}

{% block title %}Login{% endblock %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="middle-box text-center loginscreen animated fadeInDown">
            <h1 class="logo-name">HQ+</h1>
            <h2>StrataHQ Login</h2>
            {% if form.errors %}
                <div class="alert alert-danger">
                    Your username or password are incorrect. Please try again.
                </div>
            {% endif %}
            <form class="m-t" id="login-form" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group margin-bottom-sm">
                        <span class="input-group-addon"><i class="fa fa-user fa-fw" aria-hidden="true"></i></span>
                        <input type="text" class="form-control" placeholder="Username" name="username"
                               autofocus maxlength="254"
                               required id="id_username">
                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-key fa-fw" aria-hidden="true"></i></span>
                        <input type="password" class="form-control" placeholder="Password" name="password"
                               required id="id_password">
                    </div>
                </div>

                <input type="submit" value="Login"
                       class="btn btn-primary btn-lg btn-outline btn-block"/>
            </form>
        </div>
    </div>
{% endblock content %}

templates/nav.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"> {{ user.get_full_name|default:user.username }}</strong><b class="caret"></b>
                             </span> <span class="text-muted text-xs block">
                                {% for team in user.team_set.all %}
                                    {{ team }}<br />
                                {% endfor %}</span> </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="/logout">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    HQ+
                </div>
            </li>
            {% include 'home/nav.html' %}
            {% for team in user.team_set.all %}
                {% if 'strata' == team.team %}
                    {% include 'strata/nav.html' %}
                {% endif %}
            {% endfor %}
            {% include 'assets/nav.html' %}

        </ul>

    </div>
</nav>

templates/style.html
    {% load static %}
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="{% block css-bootstrap %}{% static "css/bootstrap.min.css" %}{% endblock %}" />
    <link rel="stylesheet" type="text/css" href="{% block css-fa %}{% static "font-awesome/css/font-awesome.css" %}{% endblock %}" />
    <link rel="stylesheet" type="text/css" href="{% block css-toastr %}{% static "css/plugins/toastr/toastr.min.css" %}{% endblock %}" />
    <link rel="stylesheet" type="text/css" href="{% block css-style %}{% static "css/style.css" %}{% endblock %}" />
    <link rel="stylesheet" type="text/css" href="{% block css-animate %}{% static "css/animate.css" %}{% endblock %}" />
    <link rel="stylesheet" type="text/css" href="{% block css-gritter %}{% static "js/plugins/gritter/jquery.gritter.css" %}{% endblock %}" />

    {% block extrastyle %}{% endblock %}